name: 批量构建 Magisk 模块

on:
  workflow_dispatch:

jobs:
  batch-build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 克隆仓库
        uses: actions/checkout@v3

      - name: 🛠 安装依赖
        run: |
          sudo apt update
          sudo apt-get install -y aria2 zip unzip

      - name: 🚀 执行批量构建
        run: |
          bash ./batch_build.sh

      - name: ⏰ 获取当前时间
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: 📦 上传所有构建产物
        uses: actions/upload-artifact@v4
        with:
          name: batch-build-artifacts-${{ github.run_id }}-${{ steps.datetime.outputs.datetime }}
          path: batch_dist/
